name: Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "setup/**"

concurrency: infrastructure_${{ github.ref }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: git-${{ github.sha }}
          aws-region: ap-south-1

      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ github.sha }}
          restore-keys: |
            terraform-

      - name: Init
        working-directory: resources
        run: |
          terraform -version >> $GITHUB_STEP_SUMMARY
          terraform init

      - name: Plan
        working-directory: resources
        run: |
          terraform plan
