name: Tailscale

on:
  workflow_dispatch:
    inputs:
      tf-destroy:
        type: boolean
        default: false
        description: "Terraform Destroy"


concurrency: tailscale_${{ github.ref }}

jobs:
  plan:
    environment:
      name: sandbox
      url: 'https://ap-south-1.console.aws.amazon.com/console/home'
    runs-on: ubuntu-latest
    name: Terraform plan
    permissions:
      id-token: write
      contents: read
    env:
      TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: git-${{ github.sha }}
          aws-region: ap-south-1

      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            tailscale/.terraform
            tailscale/.terraform.lock.hcl
          key: terraform-tailscale-${{ github.sha }}
          restore-keys: |
            terraform-tailscale-

      - name: Init
        working-directory: tailscale
        run: |
          terraform init

      - name: Apply
        if: inputs.tf-destroy == false
        working-directory: tailscale
        run: |
          terraform apply -auto-approve

      - name: Destroy
        if: inputs.tf-destroy
        working-directory: tailscale
        run: |
          terraform destroy -auto-approve